<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()) :?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()) :?>
                <div class="field qty">
                    <div class="quantity-container">
                        <span class="quantity-controls quantity-minus">-</span>
                        <input type="number"
                               name="qty"
                               id="qty"
                               min="0"
                               value="<?= $block->getProductDefaultQty() * 1 ?>"
                               title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                               class="qty-default input-text qty"
                               data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                        />
                            <span class="quantity-controls quantity-plus">+</span>
                            <script type="text/javascript">
                                require([
                                    'jquery'
                                ], function ($) {
                                    $('.quantity-plus').click(function () {
                                        $('.qty-default').val(Number($('.qty-default').val()) + 1);
                                    });

                                    $('.quantity-minus').click(function () {
                                        var value = Number($('.qty-default').val()) - 1;
                                        if (value > 0) {
                                            $('.qty-default').val(value);
                                        }

                                    });
                                });
                            </script>
                        <p class="stock-text"> ✓ <span>In stocks <?= $_product->getQty() ?></span> items available</p>
                    </div>
                </div>
            <?php endif; ?>
            <div class="actions">
                <button type="submit"
                        title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                        class="action primary tocart add-to-cart"
                        id="product-addtocart-button" disabled>
                    <span><?= $block->escapeHtml($buttonTitle) ?></span>
                </button>
                <?= $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
